/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzagui;

import javax.swing.JOptionPane;

/**
 *
 * @author lajko
 */
public class PizaGui extends javax.swing.JFrame {

    /**
     * Creates new form PizaGui2
     */
    public PizaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGMeret = new javax.swing.ButtonGroup();
        BtnGTeszta = new javax.swing.ButtonGroup();
        BtnGAlap = new javax.swing.ButtonGroup();
        BtnRendeles = new javax.swing.JButton();
        BtnTorles = new javax.swing.JButton();
        LblKep = new javax.swing.JLabel();
        JpRendAdat = new javax.swing.JPanel();
        TxtNeve = new javax.swing.JTextField();
        LblNeve = new javax.swing.JLabel();
        TxtTelefonszama = new javax.swing.JTextField();
        LblTelefonszama = new javax.swing.JLabel();
        LblCime = new javax.swing.JLabel();
        TxtCime = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        JpMeret = new javax.swing.JPanel();
        Rdb25cm = new javax.swing.JRadioButton();
        Rdb32cm = new javax.swing.JRadioButton();
        Rdb50cm = new javax.swing.JRadioButton();
        LblMeret = new javax.swing.JLabel();
        JpTeszta = new javax.swing.JPanel();
        RdbHagy = new javax.swing.JRadioButton();
        RdbOlasz = new javax.swing.JRadioButton();
        Lblteszta = new javax.swing.JLabel();
        RdbVastagt = new javax.swing.JRadioButton();
        JpFeltet = new javax.swing.JPanel();
        LblFeltet = new javax.swing.JLabel();
        CkbSonka = new javax.swing.JCheckBox();
        CkbKolbasz = new javax.swing.JCheckBox();
        CkbGomba = new javax.swing.JCheckBox();
        JpAlap = new javax.swing.JPanel();
        LblAlap = new javax.swing.JLabel();
        RdbParadicsom = new javax.swing.JRadioButton();
        Rdbtejfolos = new javax.swing.JRadioButton();
        RdbCsokis = new javax.swing.JRadioButton();
        LblRendAdat1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza rendelés");
        setMaximizedBounds(new java.awt.Rectangle(250, 200, 200, 200));
        setMaximumSize(new java.awt.Dimension(320, 200));
        setMinimumSize(new java.awt.Dimension(496, 259));

        BtnRendeles.setText("Rendelés");
        BtnRendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRendelesActionPerformed(evt);
            }
        });

        BtnTorles.setText("Rendelés tölrése");
        BtnTorles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTorlesActionPerformed(evt);
            }
        });

        LblKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\LajkóGergő(SZOFT_202\\Documents\\NetBeansProjects\\2023.10.18\\PizzaGui\\kepek\\pizzaa.jpg")); // NOI18N

        JpRendAdat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TxtNeve.setText("Pálda János");
        TxtNeve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNeveMouseClicked(evt);
            }
        });
        TxtNeve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNeveActionPerformed(evt);
            }
        });

        LblNeve.setText("Neve:");

        TxtTelefonszama.setText("0630/12345678");
        TxtTelefonszama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTelefonszamaMouseClicked(evt);
            }
        });
        TxtTelefonszama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonszamaActionPerformed(evt);
            }
        });

        LblTelefonszama.setText("Telefonszáma");

        LblCime.setText("Címe:");

        TxtCime.setText("1100 Budapest Példa utca 25");
        TxtCime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtCimeMouseClicked(evt);
            }
        });
        TxtCime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCimeActionPerformed(evt);
            }
        });

        LblEmail.setText("E-mail címe:");

        TxtEmail.setText("pledajanis@gmail.com");
        TxtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtEmailMouseClicked(evt);
            }
        });
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpRendAdatLayout = new javax.swing.GroupLayout(JpRendAdat);
        JpRendAdat.setLayout(JpRendAdatLayout);
        JpRendAdatLayout.setHorizontalGroup(
            JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRendAdatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTelefonszama)
                    .addComponent(LblNeve, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtNeve)
                    .addComponent(TxtTelefonszama, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRendAdatLayout.createSequentialGroup()
                        .addComponent(LblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(JpRendAdatLayout.createSequentialGroup()
                        .addComponent(LblCime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TxtCime)
                    .addComponent(TxtEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpRendAdatLayout.setVerticalGroup(
            JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRendAdatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNeve)
                    .addComponent(TxtNeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCime)
                    .addComponent(TxtCime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpRendAdatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTelefonszama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTelefonszama)
                    .addComponent(LblEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpMeret.setBorder(new javax.swing.border.MatteBorder(null));

        BtnGMeret.add(Rdb25cm);
        Rdb25cm.setSelected(true);
        Rdb25cm.setText("25 cm");
        Rdb25cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb25cmActionPerformed(evt);
            }
        });

        BtnGMeret.add(Rdb32cm);
        Rdb32cm.setText("32 cm");
        Rdb32cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb32cmActionPerformed(evt);
            }
        });

        BtnGMeret.add(Rdb50cm);
        Rdb50cm.setText("50 cm");
        Rdb50cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb50cmActionPerformed(evt);
            }
        });

        LblMeret.setText("Méret:");

        javax.swing.GroupLayout JpMeretLayout = new javax.swing.GroupLayout(JpMeret);
        JpMeret.setLayout(JpMeretLayout);
        JpMeretLayout.setHorizontalGroup(
            JpMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpMeretLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpMeretLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Rdb25cm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpMeretLayout.createSequentialGroup()
                        .addGroup(JpMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMeret, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rdb32cm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rdb50cm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpMeretLayout.setVerticalGroup(
            JpMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpMeretLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMeret)
                .addGap(5, 5, 5)
                .addComponent(Rdb25cm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rdb32cm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rdb50cm)
                .addContainerGap())
        );

        JpTeszta.setBorder(new javax.swing.border.MatteBorder(null));

        BtnGTeszta.add(RdbHagy);
        RdbHagy.setSelected(true);
        RdbHagy.setText("hagyományos");
        RdbHagy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbHagyActionPerformed(evt);
            }
        });

        BtnGTeszta.add(RdbOlasz);
        RdbOlasz.setText("olaszos");
        RdbOlasz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbOlaszActionPerformed(evt);
            }
        });

        Lblteszta.setText("Tészta:");

        BtnGTeszta.add(RdbVastagt);
        RdbVastagt.setText("vastag tésztájú");
        RdbVastagt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbVastagtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpTesztaLayout = new javax.swing.GroupLayout(JpTeszta);
        JpTeszta.setLayout(JpTesztaLayout);
        JpTesztaLayout.setHorizontalGroup(
            JpTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpTesztaLayout.createSequentialGroup()
                .addGroup(JpTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdbHagy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdbOlasz, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JpTesztaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lblteszta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpTesztaLayout.createSequentialGroup()
                .addComponent(RdbVastagt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpTesztaLayout.setVerticalGroup(
            JpTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpTesztaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lblteszta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdbHagy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdbOlasz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdbVastagt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpFeltet.setBorder(new javax.swing.border.MatteBorder(null));

        LblFeltet.setText("Feltét:");

        CkbSonka.setText("sonka");
        CkbSonka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkbSonkaActionPerformed(evt);
            }
        });

        CkbKolbasz.setText("kolbász");
        CkbKolbasz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkbKolbaszActionPerformed(evt);
            }
        });

        CkbGomba.setText("gomba");
        CkbGomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkbGombaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpFeltetLayout = new javax.swing.GroupLayout(JpFeltet);
        JpFeltet.setLayout(JpFeltetLayout);
        JpFeltetLayout.setHorizontalGroup(
            JpFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpFeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFeltet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpFeltetLayout.createSequentialGroup()
                .addGroup(JpFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CkbSonka, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CkbKolbasz, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CkbGomba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        JpFeltetLayout.setVerticalGroup(
            JpFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpFeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFeltet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CkbSonka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CkbKolbasz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CkbGomba)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        JpAlap.setBorder(new javax.swing.border.MatteBorder(null));

        LblAlap.setText("Alap:");

        BtnGAlap.add(RdbParadicsom);
        RdbParadicsom.setSelected(true);
        RdbParadicsom.setText("Paradicsomos");
        RdbParadicsom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbParadicsomActionPerformed(evt);
            }
        });

        BtnGAlap.add(Rdbtejfolos);
        Rdbtejfolos.setText("Tejfölös");
        Rdbtejfolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbtejfolosActionPerformed(evt);
            }
        });

        BtnGAlap.add(RdbCsokis);
        RdbCsokis.setText("Csokis");
        RdbCsokis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbCsokisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpAlapLayout = new javax.swing.GroupLayout(JpAlap);
        JpAlap.setLayout(JpAlapLayout);
        JpAlapLayout.setHorizontalGroup(
            JpAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAlapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblAlap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpAlapLayout.createSequentialGroup()
                .addGroup(JpAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdbParadicsom)
                    .addComponent(Rdbtejfolos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdbCsokis, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JpAlapLayout.setVerticalGroup(
            JpAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAlapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblAlap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdbParadicsom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rdbtejfolos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdbCsokis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LblRendAdat1.setText("Rendelő adatai:");
        LblRendAdat1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpRendAdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRendAdat1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnTorles)
                            .addGap(296, 296, 296)
                            .addComponent(BtnRendeles))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JpTeszta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JpAlap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JpMeret, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JpFeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblRendAdat1)
                .addGap(1, 1, 1)
                .addComponent(JpRendAdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JpFeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JpMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JpTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JpAlap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblKep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTorles)
                    .addComponent(BtnRendeles))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRendelesActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Ez egy teszt verzió");
       //Ellenörizük hogy a mezők üresek-e
       boolean vanAdat;
       vanAdat = !TxtNeve.getText().isEmpty()&& !TxtTelefonszama.getText().isEmpty() && !TxtCime.getText().isEmpty() && !TxtEmail.getText().isEmpty();
       String uzenett, cim ="Figyelem!!";
       int ikonTipus;
       //if(TxtNeve.getText().isEmpty()&& TxtTelefonszama.getText().isEmpty() && TxtCime.getText().isEmpty() && TxtEmail.getText().isEmpty());
       boolean radioKivalasztas;
       boolean ChkBoxKivalasztva; 
       radioKivalasztas = !Rdb25cm.isSelected() && !Rdb32cm.isSelected() && !Rdb50cm.isSelected() && !RdbCsokis.isSelected() && !RdbParadicsom.isSelected() && !Rdbtejfolos.isSelected() && !RdbHagy.isSelected() && !RdbOlasz.isSelected() && !RdbVastagt.isSelected();
       ChkBoxKivalasztva = !CkbSonka.isSelected() && !CkbGomba.isSelected() && !CkbKolbasz.isSelected();
       
       if(!vanAdat && !radioKivalasztas && !ChkBoxKivalasztva)
       {
            cim=  cim + "Kitöltés probléma";
            uzenett = "Nincsenek kitötltve az adatok!!!";
            ikonTipus = JOptionPane.WARNING_MESSAGE;
        
       }
       else{
            cim=  cim + "Rendelés felvéve";
            uzenett = "Rendelését felvettük. E-mailbe értesitjük, amikor elkészült.";
            ikonTipus = JOptionPane.INFORMATION_MESSAGE;//2;
        }
       
       
       
       JOptionPane.showMessageDialog(null, uzenett, cim, ikonTipus);
       
    }//GEN-LAST:event_BtnRendelesActionPerformed

    private void BtnTorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTorlesActionPerformed
        //Text mezöböl törlés
        TxtNeve.setText("");
        TxtTelefonszama.setText("");
        TxtCime.setText("");
        TxtEmail.setText("");
        
        //Radio gombok adatok törlése
        BtnGMeret.clearSelection();
        BtnGTeszta.clearSelection();
       // BtnGFeltet.clearSelection();
        BtnGAlap.clearSelection();

        // Töröld a checkboxok kiválasztását
        CkbSonka.setSelected(false);
        CkbKolbasz.setSelected(false);
        CkbGomba.setSelected(false);
        
    }//GEN-LAST:event_BtnTorlesActionPerformed

    private void TxtNeveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNeveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNeveActionPerformed

    private void TxtCimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCimeActionPerformed

    private void TxtTelefonszamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonszamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonszamaActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void Rdb25cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb25cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdb25cmActionPerformed

    private void Rdb32cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb32cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdb32cmActionPerformed

    private void Rdb50cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb50cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdb50cmActionPerformed

    private void RdbHagyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbHagyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbHagyActionPerformed

    private void RdbOlaszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbOlaszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbOlaszActionPerformed

    private void RdbVastagtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbVastagtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbVastagtActionPerformed

    private void CkbSonkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkbSonkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CkbSonkaActionPerformed

    private void CkbKolbaszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkbKolbaszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CkbKolbaszActionPerformed

    private void CkbGombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkbGombaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CkbGombaActionPerformed

    private void RdbParadicsomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbParadicsomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbParadicsomActionPerformed

    private void RdbtejfolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbtejfolosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbtejfolosActionPerformed

    private void RdbCsokisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbCsokisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbCsokisActionPerformed

    private void TxtNeveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNeveMouseClicked
        TxtNeve.setText("");
    }//GEN-LAST:event_TxtNeveMouseClicked

    private void TxtCimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCimeMouseClicked
        TxtCime.setText("");
    }//GEN-LAST:event_TxtCimeMouseClicked

    private void TxtTelefonszamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTelefonszamaMouseClicked
       TxtTelefonszama.setText("");
    }//GEN-LAST:event_TxtTelefonszamaMouseClicked

    private void TxtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEmailMouseClicked
       TxtEmail.setText("");
    }//GEN-LAST:event_TxtEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGAlap;
    private javax.swing.ButtonGroup BtnGMeret;
    private javax.swing.ButtonGroup BtnGTeszta;
    private javax.swing.JButton BtnRendeles;
    private javax.swing.JButton BtnTorles;
    private javax.swing.JCheckBox CkbGomba;
    private javax.swing.JCheckBox CkbKolbasz;
    private javax.swing.JCheckBox CkbSonka;
    private javax.swing.JPanel JpAlap;
    private javax.swing.JPanel JpFeltet;
    private javax.swing.JPanel JpMeret;
    private javax.swing.JPanel JpRendAdat;
    private javax.swing.JPanel JpTeszta;
    private javax.swing.JLabel LblAlap;
    private javax.swing.JLabel LblCime;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFeltet;
    private javax.swing.JLabel LblKep;
    private javax.swing.JLabel LblMeret;
    private javax.swing.JLabel LblNeve;
    private javax.swing.JLabel LblRendAdat1;
    private javax.swing.JLabel LblTelefonszama;
    private javax.swing.JLabel Lblteszta;
    private javax.swing.JRadioButton Rdb25cm;
    private javax.swing.JRadioButton Rdb32cm;
    private javax.swing.JRadioButton Rdb50cm;
    private javax.swing.JRadioButton RdbCsokis;
    private javax.swing.JRadioButton RdbHagy;
    private javax.swing.JRadioButton RdbOlasz;
    private javax.swing.JRadioButton RdbParadicsom;
    private javax.swing.JRadioButton RdbVastagt;
    private javax.swing.JRadioButton Rdbtejfolos;
    private javax.swing.JTextField TxtCime;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNeve;
    private javax.swing.JTextField TxtTelefonszama;
    // End of variables declaration//GEN-END:variables
}
